"""empty message

Revision ID: 1733fc53374c
Revises: 1d0760109e23
Create Date: 2021-08-06 17:00:31.209344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1733fc53374c'
down_revision = '1d0760109e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookedroom', sa.Column('hostel_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookedroom', 'hostel', ['hostel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookedroom', type_='foreignkey')
    op.drop_column('bookedroom', 'hostel_id')
    # ### end Alembic commands ###
