"""empty message

Revision ID: 1ae912cd865b
Revises: 1c5a313d2fb7
Create Date: 2021-06-28 18:49:06.520737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae912cd865b'
down_revision = '1c5a313d2fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('h_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'room', 'hostel', ['h_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_column('room', 'h_id')
    # ### end Alembic commands ###
