"""empty message

Revision ID: 1d0760109e23
Revises: 1ae912cd865b
Create Date: 2021-06-28 18:50:05.368921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d0760109e23'
down_revision = '1ae912cd865b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'room', 'hostel', ['hostel_id'], ['id'])
    op.drop_column('room', 'h_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('h_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'room', type_='foreignkey')
    # ### end Alembic commands ###
