"""empty message

Revision ID: 2ce23b039f1e
Revises: 959aeda7e48b
Create Date: 2021-08-06 20:42:19.712971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce23b039f1e'
down_revision = '959aeda7e48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('management', sa.String(length=300), nullable=False))
    op.add_column('hostel', sa.Column('rooms', sa.Integer(), nullable=False))
    op.add_column('hostel', sa.Column('caretaker', sa.String(length=300), nullable=False))
    op.add_column('hostel', sa.Column('contact', sa.String(length=10), nullable=False))
    op.add_column('hostel', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel', 'description')
    op.drop_column('hostel', 'contact')
    op.drop_column('hostel', 'caretaker')
    op.drop_column('hostel', 'rooms')
    op.drop_column('hostel', 'management')
    # ### end Alembic commands ###
