"""empty message

Revision ID: 7e37b20adc95
Revises: cdeada980366
Create Date: 2021-06-25 13:51:22.207873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e37b20adc95'
down_revision = 'cdeada980366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('management', sa.String(length=300), nullable=False),
    sa.Column('rooms', sa.String(length=100), nullable=False),
    sa.Column('caretaker', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hostel_name'), 'hostel', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hostel_name'), table_name='hostel')
    op.drop_table('hostel')
    # ### end Alembic commands ###
