"""empty message

Revision ID: 959aeda7e48b
Revises: c7acf29d7e8a
Create Date: 2021-08-06 20:42:04.617043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959aeda7e48b'
down_revision = 'c7acf29d7e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel', 'rooms')
    op.drop_column('hostel', 'management')
    op.drop_column('hostel', 'description')
    op.drop_column('hostel', 'caretaker')
    op.drop_column('hostel', 'contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('contact', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('hostel', sa.Column('caretaker', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('hostel', sa.Column('description', mysql.TEXT(), nullable=False))
    op.add_column('hostel', sa.Column('management', mysql.VARCHAR(length=300), nullable=False))
    op.add_column('hostel', sa.Column('rooms', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
