"""empty message

Revision ID: b602f684b185
Revises: 7e37b20adc95
Create Date: 2021-06-25 15:36:51.319935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b602f684b185'
down_revision = '7e37b20adc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.String(length=300), nullable=False),
    sa.Column('size', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=300), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hostel', 'rooms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('rooms', mysql.VARCHAR(length=100), nullable=False))
    op.drop_table('room')
    # ### end Alembic commands ###
