"""empty message

Revision ID: c595a202213b
Revises: d7b107096e4f
Create Date: 2021-06-25 13:04:51.971117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c595a202213b'
down_revision = 'd7b107096e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hostel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('management', sa.String(length=300), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=False),
    sa.Column('caretaker', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'rooms')
    )
    op.create_index(op.f('ix_hostel_name'), 'hostel', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hostel_name'), table_name='hostel')
    op.drop_table('hostel')
    # ### end Alembic commands ###
