"""empty message

Revision ID: c7acf29d7e8a
Revises: 1733fc53374c
Create Date: 2021-08-06 18:08:23.535829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c7acf29d7e8a'
down_revision = '1733fc53374c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('status', mysql.VARCHAR(length=300), nullable=False))
    # ### end Alembic commands ###
