"""empty message

Revision ID: d4638d27d3e5
Revises: c595a202213b
Create Date: 2021-06-25 13:38:19.719370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4638d27d3e5'
down_revision = 'c595a202213b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hostel', sa.Column('place', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hostel', 'place')
    # ### end Alembic commands ###
