"""empty message

Revision ID: d7b107096e4f
Revises: f315d88f9e3f
Create Date: 2021-06-23 18:01:24.489578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7b107096e4f'
down_revision = 'f315d88f9e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Fname')
    op.drop_column('user', 'image')
    op.drop_column('user', 'about')
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'Lname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Lname', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('user', sa.Column('member_since', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('about', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('image', mysql.VARCHAR(length=150), nullable=True))
    op.add_column('user', sa.Column('Fname', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
