"""empty message

Revision ID: fd8d8427391a
Revises: 2ce23b039f1e
Create Date: 2021-08-17 12:44:28.960526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8d8427391a'
down_revision = '2ce23b039f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.add_column('bookedroom', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_constraint('bookedroom_ibfk_2', 'bookedroom', type_='foreignkey')
    op.drop_column('bookedroom', 'hostel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookedroom', sa.Column('hostel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('bookedroom_ibfk_2', 'bookedroom', 'hostel', ['hostel_id'], ['id'])
    op.drop_column('bookedroom', 'date')
    op.create_table('transactions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone_no', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
